export const projects = [
    {
      name: "Website Medical Care",
      imgSrc: "/aset/BAHALYmed.jpg.png",
      Url: "https://ibraiiian.github.io/Bahalymed.Dibimbing/",
      content:
        "Built with HTML, CSS, and Bootstrap, this website provides a user-friendly and responsive platform for exploring medical services and booking health",
      imgBuild:  "",
      svg2: "",
      svg3: "",
      initial: { scale: 0.9 },
      whileInVIew: { scale: 1, transition: { type: "spring", duration: 1 } },
    },
    {
      name: "AT-Taqwa Travel Website",
      imgSrc: "/aset/AT-taqwa travel web.jpg.png",
      Url: "https://at-taqwa-travel.vercel.app/",
      content:
        "Powered by React.js and Tailwind CSS, this website offers a smooth and efficient way to explore and book Hajj and Umrah packages",
      imgBuild: "",
      svg2: "",
      svg3: "",
      initial: { scale: 0.9 },
      whileInVIew: { scale: 1, transition: { type: "spring", duration: 1 } },
    },
    {
      name: "Brams Coffe",
      imgSrc: "/aset/bramscoffe.png",
      Url: "https://ibraiiian.github.io/bramscoffe/",
      content: "Built with HTML, CSS, JavaScript, and Bootstrap, Bram's Coffee offers an easy way to explore and order coffee. Enjoy a seamless experience from browsing to checkout",
      imgBuild: "",
      svg4: "",
      svg: "",
      svg3: "",
      initial: { scale: 0.9 },
      whileInVIew: { scale: 1, transition: { type: "spring", duration: 1 } },
    },
    {
      name: "Landing Page",
      imgSrc: "/aset/1edit.jpg",
      Url: "https://slicing-landing-page-theta.vercel.app/",
      content: "Slicing Simple modern Design Frontend From Figma To React with framer motion and tailwind css",
      svg4: "",
      svg: "",
      svg2:"",
      initial: { scale: 0.9 },
      whileInVIew: { scale: 1, transition: { type: "spring", duration: 1 } },
    },
    {
      name: "Landing Page Portofolio",
      imgSrc: "/aset/DigiTech.id.png",
      Url: "https://digitech-id.vercel.app/#kontak",
      content:
        "Built with TypeScript and Tailwind CSS, DigiTech.id offers innovative solutions for digital transformation.",
      imgBuild: "",
      svg2: "",
      svg3: "",
      initial: { scale: 0.9 },
      whileInVIew: { scale: 1, transition: { type: "spring", duration: 1 } },
    },
  ];